# Generated by Django 5.2.8 on 2026-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
