# Generated by Django 5.2.8 on 2026-01-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilefollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ProfileEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('degrees', models.JSONField(blank=True, default=list)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='profiles.profile')),
            ],
            options={
                'ordering': ['-is_current', '-end_year', '-start_year'],
                'indexes': [models.Index(fields=['profile', '-is_current'], name='profiles_pr_profile_53b571_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('location_type', models.CharField(choices=[('current', 'Current'), ('previous', 'Previous'), ('hometown', 'Hometown'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='profiles.profile')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['profile', '-is_primary'], name='profiles_pr_profile_2f3bdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('self-employed', 'Self-employed'), ('freelance', 'Freelance'), ('contract', 'Contract'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship'), ('seasonal', 'Seasonal')], max_length=50, null=True)),
                ('start_year', models.IntegerField()),
                ('start_month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('description', models.TextField(blank=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='profiles.profile')),
            ],
            options={
                'ordering': ['-is_current', '-end_year', '-start_year'],
                'indexes': [models.Index(fields=['profile', '-is_current'], name='profiles_pr_profile_95858e_idx')],
            },
        ),
    ]
