# Generated by Django 5.2.8 on 2026-01-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_account_type_user_company_user_current_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
    ]
